# Generated by Django 4.2.5 on 2024-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='temporary_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
