# Generated by Django 4.2.5 on 2024-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_invoice_temporary_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_prof_service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_reimbur_service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
